name: Run Tests and Linting

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.11]  # Add other Python versions if needed

    steps:
    - uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
        architecture: x64

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Unit Tests
      run: python manage.py test

    - name: Run Integration Tests
      run: pytest

    - name: Run Flake8 and Black
      run: |
        pip install flake8 black
        flake8 .
        black --check --diff .
